### ISSUE TITLE
メモの新規保存機能の実装

### ISSUE THREAD

**Issue by Ta23ka98** [yusakufujita/memory#12]
realmを使ってメモの新規保存機能を実装する。
その際はCRUD命名規則に従い、共通化する。

## 期限
・2/7

**Comment by yusakufujita** [comment]
https://github.com/yusakufujita/memory/issues/15 のコメントにヒント

**Comment by Ta23ka98** [comment]
ちょっと悩んでいるのですが、
・Memoモデルを作り、それぞれの属性をnullableにする
・〇〇Memoモデルなど、それぞれに対応するモデルを作る
で迷っています🤔

<img width="651" alt="スクリーンショット 2023-02-05 22 52 58" src="https://user-images.githubusercontent.com/79580546/216823516-5467cd30-90bc-4756-ae01-7f31d72e3b23.png">

**Comment by Ta23ka98** [comment]
@yusakufujita 
↑ひとまずクラスは別で用意しました。
現在はProviderを使ってCRUDをほぼ実装完了、後はメモ表示で確認していく感じです。

因みにローカルDBにはユーザModelって必要なんでしょうか？
必要であればサンプルをそのまま、必要なければ少しアレンジして実装完了という感じです

**Comment by yusakufujita** [comment]
@Ta23ka98 
ユーザモデルというのは、ユーザの情報を保存するモデルですよね?
必要ないですね

**Comment by Ta23ka98** [comment]
@yusakufujita 
なるほど、ありがとうございます！

**Comment by yusakufujita** [comment]
@Ta23ka98 
できたら、見るので、PR出してください
