### ISSUE TITLE
Home画面のListileが仕様の通りにタップした場所に遷移しない

### ISSUE THREAD

**Issue by yusakufujita** [yusakufujita/memory#16]
<img src="https://user-images.githubusercontent.com/48333289/216375554-0cc8e9c0-0949-4117-983f-6bfff2c8a8ef.png" width= "320px" > |

上記の青枠で囲った箇所をタップすると、per_ide_num.dartファイルに遷移してしまう

**Comment by Ta23ka98** [comment]
こちら対応完了です✅
ListTileのtrailing（メモ編集アイコン）に画面遷移するよう実装したつもりでしたが、よく見たらListTile自体の画面遷移として実装していました🙇

改めてメモ編集アイコン自体をGestureDetectorでラップすることで、タップで画面遷移する領域をアイコンに限定しました！
