### ISSUE TITLE
対応するメモ編集画面に画面遷移する機能実装

### ISSUE THREAD

**Issue by Ta23ka98** [yusakufujita/memory#18]
## 概要
現在、メモ編集アイコンをタップするとPerIdeNumに画面遷移する。
しかし実際は暗証番号や銀行口座、クレカのパスワード画面などの対応する画面に遷移する必要がある。

このIssueでは、その方法を考えて実装していく。

**Comment by Ta23ka98** [comment]
現在PerIdeNumがメモ編集画面だと思うのですが、このパターンを増やしてテンプレートのようにするのが良いと思います🙋

やり方としては単純で、
①StatefulWidgetを作り、適切な名前（PinMemo, BankMemo, CreditMemoなど）をつける
②既にPerIdeNumでやったように、いくつかのフォームを組み合わせ、対応するメモ編集画面にしていく

基本的にはこれでOKだと思います！
ただウィジェットは16種類以上になると思うで、慣れたらタイトル/必要なフォームをListか何かで管理した方が良さげですね🤔

**Comment by yusakufujita** [comment]
なるほど

それは、わかるのですが、

現状だとmain.Dartで銀行号座の新規メモボタンを押しても、全て暗証番号(PerIdeNum)になってしまうので、それを区別する方法が知りたいです

**Comment by yusakufujita** [comment]
また、titleList画面に遷移した時も、全て暗証番号になってしまいます。
![Uploading simulator_screenshot_8B980FC2-51F1-489F-ACFF-2D3F18C82350.png…]()

**Comment by Ta23ka98** [comment]
なるほど！遷移後の画面を実装することは把握済みで、遷移先を区別する方法ですね！
アプリの仕様についての確認なのですが、ホーム画面にある一覧は固定なのでしょうか？（暗証番号、銀行口座...のリスト）

もし固定であれば、List<String> titleで管理しているように、遷移後の画面もListで管理しましょう👍
今は画面遷移のメソッドをnavigationTo~と個別に実装していますが、これもListViewのindexの引数を渡すかたちで管理できると思います🙋

もし固定でないならば...
一旦アプリの仕様について確認が必要かもです🤔
