### ISSUE TITLE
UIエラー"RenderFlexOverflowed"の根本的な解決方法・原因を探る

### ISSUE THREAD

**Issue by Ta23ka98** [yusakufujita/memory#5]
## 参考記事
・https://zenn.dev/flutteruniv_dev/articles/532d0a9464c562

**Comment by Ta23ka98** [comment]
改めて記事を読んだところ、認識は間違っていませんでした。
やっぱり手元で試さないとダメそうですね。

MTG時にはRowにFlexibleやSizedBoxを使ってエラーが出ていました。このエラーが
・ListTileの大きさをはみ出しているエラーか
・Rowの子ウィジェット(Text2つ)が、指定した大きさに入りきらないエラーか
これらを見極める必要がありそうです。

**Comment by Ta23ka98** [comment]
ひとまず対応完了です✅

<img width="339" alt="スクリーンショット 2023-01-30 16 54 23" src="https://user-images.githubusercontent.com/79580546/215419137-33f39bcf-72bf-4e1c-9356-fee5c464e0af.png">

**Comment by Ta23ka98** [comment]
やったことは、ListTile→Rowにある...

①TextウィジェットをSizedBoxでラップし、widthを120とする
②間にあるSizedBoxは不要のため、削除
③MainAxisAlignment.をspaceBetweenに変更
の3つです

分からないことがあれば、また気軽に訊いてください👍

**Comment by yusakufujita** [comment]
解決したのcloseにしました

**Comment by yusakufujita** [comment]
僕のところだと折り畳まれないですね

うーん
iPhoneの機種は、なんですか?

**Comment by Ta23ka98** [comment]
なるほど、確かにそこは重要ですね！
僕のシミュレータではiPhone 14 Pro Maxを使っています🙋

機種ごとにサイズを合わせる方法も調べておきますね👍

**Comment by yusakufujita** [comment]
今、確認したんですが、
width:100が確かに折り畳まれていました。
なので、width:120にしたんですが、RenderFlexOverflowedのエラーがでてしまいます。

**Comment by yusakufujita** [comment]
width:108ですね
![simulator_screenshot_59B644A1-4575-40F4-AF9A-608589DAD5A9](https://user-images.githubusercontent.com/48333289/215719501-06a53674-c9eb-482c-acd3-9261be4285c8.png)
